### ISSUE TITLE
authentication can fails when identity domain != scope domain

### ISSUE THREAD

**Issue by jan--f** [ggiamarchi/vagrant-openstack-provider#361] opened 2018-07-13 15:08 UTC
Trying to use this provider with an openstack instance where a scoped authentication requires an identity domain name that is different from a scope's project domain, this provider does not work.

**Comment by ggiamarchi** [comment] 2018-07-26 10:50
This issue is actually a duplicate of #334

**Closed by ggiamarchi** 2018-07-26 10:50 UTC
